###
Generated by coffee-script, any changes should be made to the adagios.coffee file
###
#
# Allow radio inputs as button in regular form
# http://dan.doezema.com/2012/03/twitter-bootstrap-radio-button-form-inputs/
#
# This stops regular posting for buttons and assigns values to a hidden input
# to enable buttons as a radio.
#

jQuery ($) ->
  $("div.btn-group[data-toggle-name=\"*\"]").each ->
    group = $(this)
    form = group.parents("form").eq(0)
    name = group.attr("data-toggle-name")
    hidden = $("input[name=\"#{ name }\"]", form)
    $("button", group).each ->
      button = $(this)
      button.live "click", ->
        hidden.val $(this).val()

      button.addClass "active"  if button.val() is hidden.val()



$.extend $.fn.dataTableExt.oStdClasses,
  sSortAsc: "header headerSortDown"
  sSortDesc: "header headerSortUp"
  sSortable: "header"

(($) ->
  obIgnoreTables = [$("table#service")[0], $("table#contact")[0], $("table#host")[0], $("table#command")[0], $("table#timeperiod")[0]]
  filter_cache = {}
  object_types = ['service', 'servicegroup', 'host', 'hostgroup', 'contact', 'contactgroup', 'command', 'timeperiod']

  $.fn.dataTableExt.afnFiltering.push (oSettings, aData) ->
    # Disable filter for all tables except obIgnoreTables
    return true  if $.inArray(oSettings.nTable, obIgnoreTables) is -1

    # Default we show nothing
    object_type = oSettings["sTableId"]

    return true if filter_cache[object_type] is undefined

    # We are showing templates and this is register=0
    if aData[0] is "0" and filter_cache[object_type] is "2"
      return true

    if filter_cache[object_type] is "1" and aData[1] is "#{object_type}group" and aData[0] != "0"
      return true

    if filter_cache[object_type] is "0" and aData[1] is object_type and aData[0] != "0"
      return true

    # default no
    false

  
  #
  #     Creates a dataTable for adagios objects
  #
  #     aoColumns are used primarily for Titles
  #     example, aoColumns = [ { 'sTitle': 'Contact Name'}, { 'sTitle': 'Alias' } ]
  #
  #     
  $.fn.adagios_ob_configure_dataTable = (aoColumns, fetch) ->
    
    # Option column
    aoColumns.unshift
      sTitle: "register"
      bVisible: false
    ,
      sTitle: "object_type"
      bVisible: false
    ,
      sTitle: """<label rel="tooltip" title="Select All" id="selectall" class="checkbox"><input type="checkbox"></label>"""
      sWidth: "32px"

    aoColumns.push
      sTitle: "Actions"
      sWidth: "32px"

    $this = $(this)
    $this.data "fetch", fetch
    $this.data "aoColumns", aoColumns
    $this

  $.fn.adagios_ob_render_dataTable = ->
    $this = $(this)
    $this.dtData = []
    $this.fetch = $this.data("fetch")
    $this.aoColumns = $this.data("aoColumns")
    $this.jsonqueries = $this.fetch.length
    $.each $this.fetch, (f, v) ->
      object_type = v["object_type"]
      console.log """Populating #{ object_type } #{ $(this).attr("id") }<br/>"""
      json_query_fields = ["id", "register"]
      $.each v["rows"], (k, field) ->
        json_query_fields.push field["cName"]  if "cName" of field
        json_query_fields.push field["cAltName"]  if "cAltName" of field
        json_query_fields.push field["cHidden"]  if "cHidden" of field

      $.getJSON("../rest/pynag/json/get_objects",
        object_type: object_type
        with_fields: json_query_fields.join(",")
      , (data) ->
        count = data.length
        $.each data, (i, item) ->
          field_array = [
            item["register"],
            object_type,
            """<input id="ob_mass_select" name="#{ item["id"] }" type="checkbox">"""
          ]
          $.each v["rows"], (k, field) ->
            cell = """<a href="id=#{ item["id"] }">"""
            field_value = ""
            cell += """<i class="#{ field.icon }"></i>"""  if "icon" of field
            if item[field["cName"]]
              field_value = item[field["cName"]]
            else
              field_value = item[field["cAltName"]]  if item[field["cAltName"]]
            field_value = field_value.replace("\"", "&quot;")
            field_value = field_value.replace(">", "&gt;")
            field_value = field_value.replace("<", "&lt;")
            if "truncate" of field and field_value.length > (field["truncate"] + 3)
              cell += """<abbr rel="tooltip" title=" #{ field_value }">#{ field_value.substr(0, field["truncate"]) } ...</abbr>"""
            else
              cell += field_value
            cell += "</a>"
            field_array.push cell
            if field["cName"] is v["rows"][v["rows"].length - 1]["cName"]
              $this.dtData.push field_array
              count--

          field_array.push """
            <a rel="tooltip" title="Delete object" href="delete_object/id=#{ item["id"] }">
              <i class=\"icon-trash\"></i>
            </a>
            <a rel="tooltip" title="Copy object" href="copy_object/id=#{ item["id"] }">
              <i class=\"glyph-tags\"></i>
            </a>
            """
      ).success(->
        $this.jsonqueries = $this.jsonqueries - 1
        if $this.jsonqueries is 0
          $("[rel=tooltip]").tooltip()
          $this.data "dtData", $this.dtData
          $this.adagios_ob_dtPopulate()
      ).error (jqXHR) ->

      
      # TODO - fix this to a this style 
      
      #targetDataTable = $(this).data('datatable');
      #targetDataTable.parent().parent().parent().html('<div class="alert alert-error"><h3>ERROR</h3><br/>Failed to fetch data::<p>URL: ' + this.url + '<br/>Server Status: ' + jqXHR.status + ' ' + jqXHR.statusText + '</p></div>');
      this


  
  #
  #     Populates the datatable
  #
  #     jsonFields are used for describing which fields to fetch via json and how to handle them
  #     example, jsonFields = [ { 'cName': "command_name", 'icon_class': "glyph-computer-proces" }, ... ]
  #
  #     object_type is one of contact, command, host, service, timeperiod
  #     example, object_type = host
  #     
  $.fn.adagios_ob_dtPopulate = ->
    $this = $(this)
    object_type = $this.attr('id')
    dtData = $this.data("dtData")
    aoColumns = $this.data("aoColumns")
    $("##{ object_type } #loading").hide()
    dt = $this.dataTable(
      aoColumns: aoColumns
      sPaginationType: "bootstrap"
      # "sScrollY":"260px",
      # "bAutoWidth":true,
      bScrollCollapse: false
      bPaginate: true
      iDisplayLength: 200
      aaData: dtData
      sDom: "<'row-fluid'<'span7'<'toolbar_#{ object_type }'>>'<'span5'f>r>t<'row-fluid'<'span6'i><'span6'p>>"
      # Callback which assigns tooltips to visible pages
      fnDrawCallback: ->
        $("[rel=tooltip]").tooltip()
        $("input").click ->
          checked = $("input#ob_mass_select:checked").length
          $("#bulkselected").html checked
          if checked > 0
            $("a.bulk").removeClass "inactive"
          else
            $("a.bulk").addClass "inactive"

    )

    # Unbind sorting on the first visible column
    $("table\##{ object_type } th:first").unbind "click"

    $(".toolbar_#{ object_type }").html """
    <div class="row-fluid">
    </div>
    """
    if object_type != "command" and object_type != "timeperiod"
      $(".toolbar_#{ object_type } div.row-fluid").append """
        <div class="span4">
          <div id="view_filter" class="btn-group"></div>
        </div>"""
    $(".toolbar_#{ object_type } div.row-fluid").append """
      <div class="span8">
        <div id="add" class="btn-group">
          <a href="../../objectbrowser/add/#{ object_type }" class="btn capitalize">
            Add #{ object_type }
          </a>
          <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
            <i class="caret"></i>
          </a>
          <ul class="dropdown-menu nav">
            <li class="nav-header">Add</li>
          </ul>
         </div>
      </div>
    """

    if (object_type != "command" and object_type != "timeperiod")
      $(".toolbar_#{ object_type } div.row-fluid ul.dropdown-menu").append """
      <li><a href="../../objectbrowser/add/#{ object_type}group" class="capitalize">#{object_type}group</a></li>
      <li class="divider"></li>"""
      $(".toolbar_#{ object_type } div#view_filter.btn-group").append """
      <a rel="tooltip" title="Show #{ object_type }s" class="btn active" data-filter-type="0">
        <i class="glyph-computer-service"></i>
      </a>
      <a rel="tooltip" title="Show #{ object_type }groups" class="btn" data-filter-type="1">
        <i class="glyph-parents"></i>
      </a>
      <a rel="tooltip" title="Show #{ object_type } templates" class="btn" data-filter-type="2">
        <i class="glyph-cogwheels"></i>
      </a>"""

      filter_cache[object_type] = "0"

    for ot in object_types
      if ot is object_type or ot is "#{object_type}group"
        continue
      $(".toolbar_#{ object_type } div.row-fluid ul.dropdown-menu").append """
      <li class="capitalize"><a href="../../objectbrowser/add/#{ ot }">#{ ot }</a></li>
      """

    console.log "Assignin click on #" + object_type + ".tab-pane label#selectall"
    $("#" + $this.attr("id") + ".tab-pane label#selectall").on "click", () ->
      $checkbox = $("#" + $this.attr("id") + ".tab-pane #selectall input")
      console.log "#" + $this.attr("id") + ".tab-pane #selectall input"
      unless $checkbox.attr("checked") is `undefined`
        
        #$checkbox.attr('checked', 'checked');
        $(".tab-pane.active .dataTable input").each ->
          $(this).attr "checked", "checked"

      else
        
        #$checkbox.removeAttr('checked');
        $(".tab-pane.active .dataTable input").each ->
          $(this).removeAttr "checked"

      checked = $("input#ob_mass_select:checked").length
      $("#bulkselected").html checked
      if checked > 0
        $("a.bulk").removeClass "inactive"
      else
        $("a.bulk").addClass "inactive"

    
    # When inputs are selected in toolbar, we call redraw on the datatable which calls the filtering routing
    #        above 
    $("[class^=\"toolbar_\"] div#view_filter.btn-group a").on "click", (e) ->
      $target = $(this)
      e.preventDefault()
      return false  if $target.hasClass("active")
      object_type = $target.parentsUntil(".tab-content", ".tab-pane").attr("id")
      $target.siblings().each ->
        $(this).removeClass "active"

      $target.addClass "active"
      filter_cache[object_type] = $target.attr('data-filter-type')
      $("table#" + object_type).dataTable().fnDraw()
      false

    $("div##{object_type}_filter.dataTables_filter input").addClass "input-medium search-query"

    dt.fnSort [[3, "asc"], [4, "asc"]]

  
  #return this.each(function() {
  
  #
  #     Object Browser, This runs whenever "Run Check Plugin" is clicked
  #
  #     It resets the color of the OK/WARNING/CRITICAL/UNKNOWN button
  #     Runs a REST call to run the check_command and fetch the results
  #
  #     Calling button/href needs to have data-object-id="12312abc...."
  #     
  $.fn.adagios_ob_run_check_command = ->
    
    # Fetch the calling object
    modal = $(this)
    
    # Get the object_id
    id = modal.attr("data-object-id")
    unless id
      alert "Error, no data-object-id for run command"
      return false
    
    # Reset the class on the button
    $("#run_check_plugin #state").removeClass "label-important"
    $("#run_check_plugin #state").removeClass "label-warning"
    $("#run_check_plugin #state").removeClass "label-success"
    $("#run_check_plugin #state").html "Pending"
    $("#run_check_plugin #output pre").html "Executing check plugin"
    plugin_execution_time = $("#run_check_plugin div.progress").attr("data-timer")
    if plugin_execution_time > 1
      updateTimer = ->
        step += 1
        $("#run_check_plugin div.bar").css "width", step * 5 + "%"
        setTimeout updateTimer, step * steps  if step < 20
      $("#run_check_plugin div.progress").show()
      bar = $("#run_check_plugin div.bar")
      step = 0
      steps = (plugin_execution_time / 20) * 100
      updateTimer()
    
    # Run the command and fetch the output JSON via REST
    
    # Default to unknown if data[0] is less than 3
    
    # Set the correct class for state coloring box
    
    # Fill it up with the correct status
    
    # Put the plugin output in the correct div
    
    # Show the refresh button
    
    # Assign this command to the newly shown refresh button
    $.getJSON(BASE_URL + "rest/pynag/json/run_check_command",
      object_id: id
    , (data) ->
      statusLabel = "label-inverse"
      statusString = "Unknown"
      if data[0] is 2
        statusLabel = "label-important"
        statusString = "Critical"
      if data[0] is 1
        statusLabel = "label-warning"
        statusString = "Warning"
      if data[0] is 0
        statusLabel = "label-success"
        statusString = "OK"
      $("#run_check_plugin #state").addClass statusLabel
      $("#run_check_plugin #state").html statusString
      if data[1]
        $("#run_check_plugin div#output pre").text data[1]
      else
        $("#run_check_plugin #output pre").html "No data received on stdout"
      if data[2]
        $("#run_check_plugin #error pre").text data[2]
        $("#run_check_plugin div#error").show()
      $("#run_check_plugin_refresh").show()
      $("#run_check_plugin div.progress").hide()
      $("#run_check_plugin_refresh").click ->
        $(this).adagios_ob_run_check_command()

    ).error (jqXHR) ->
      
      # TODO - fix this to a this style 
      alert "Failed to fetch data: URL: \"" + @url + "\" Server Status: \"" + jqXHR.status + "\" Status: \"" + jqXHR.statusText + "\""

    
    # Stop the button from POST'ing
    this
) jQuery
$(document).ready ->
  $("[rel=tooltip]").popover()
  $("#popover").popover()
  $("select").chosen()

